StockControl/StockControl/StockControl/Controllers/CadastrosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using StockControl.Models;
using StockControl.Models.ViewModels;
using StockControl.Repositories;
using System.Diagnostics;
//Autor:Novadson Thelus

namespace StockControl.Controllers
{
    public class CadastrosController : Controller
    {
        private readonly ApplicationContext contexto;
        private readonly FornecedorRepository fornecedorRepository;
        private readonly ProdutoRepository produtoRepository;
        private readonly ClienteRepository clienteRepository;
        private readonly FuncionarioRepository funcionarioRepository;
        private readonly VendaRepository vendaRepository;
        private readonly IHttpContextAccessor httpContext;

        public CadastrosController(ApplicationContext contexto,
            FornecedorRepository fornecedorRepository, ProdutoRepository produtoRepository,
            ClienteRepository clienteRepository, FuncionarioRepository funcionarioRepository,
            VendaRepository vendaRepository, IHttpContextAccessor httpContext)
        {
            this.contexto = contexto;
            this.fornecedorRepository = fornecedorRepository;
            this.produtoRepository = produtoRepository;
            this.clienteRepository = clienteRepository;
            this.funcionarioRepository = funcionarioRepository;
            this.vendaRepository = vendaRepository;
            this.httpContext = httpContext;
        }

        public IActionResult Index()
        {

            var IdUsuario = HttpContext.Session.GetInt32("IdUsuario");

            if (IdUsuario != null)
            {
                return View();

            }
            return RedirectToAction("Login", "Usuario");
        }

        /*Inicial Fornecedor*/

        public IActionResult CadFornecedor()
        {
            var IdUsuario = HttpContext.Session.GetInt32("IdUsuario");

            if (IdUsuario != null)
            {
                return View();

            }
            return RedirectToAction("Login", "Usuario");
        }

        public IActionResult FornecedoresCadastrados()
        {
            var IdUsuario = HttpContext.Session.GetInt32("IdUsuario");

            if (IdUsuario != null)
            {
                return View(fornecedorRepository.GetFornecedorList());
            }
            return RedirectToAction("Login", "Usuario");

        }


        [HttpPost]
        public IActionResult CadastrarFornecedor(Fornecedor fornecedor, int Id)
        {
            var forne = new Fornecedor();

            if (ModelState.IsValid && Id > 0)
            {
                fornecedorRepository.EditarFornecedor(fornecedor, Id);
            }
            else
            {
                fornecedorRepository.AddFornecedor(fornecedor);
            }

            return RedirectToAction(nameof(FornecedoresCadastrados));
        }

        public IActionResult EditarFornecedor(int Id)
        {
            return View(nameof(CadFornecedor),
                fornecedorRepository.GetFornecedorById(Id));
        }



        public IActionResult DetalhesDoFornecedor(int Id)
        {
            return View(fornecedorRepository.GetFornecedorById(Id));
        }

        public IActionResult ExcluirFornecedor(int Id)
        {
            fornecedorRepository.ExcluirFornecedor(Id);
            return RedirectToAction(nameof(FornecedoresCadastrados));
        }

        /*Fim Fornecedor ↑ */

        [HttpGet]
        public IActionResult CadProduto()
        {
            var IdUsuario = HttpContext.Session.GetInt32("IdUsuario");

            if (IdUsuario != null)
            {
                var produtoViewModel = new ProdutoViewModel()
                {
                    GetFornecedores = fornecedorRepository.GetFornecedorListAtivo()
                };
                return View(produtoViewModel);
            }
            return RedirectToAction("Login", "Usuario");
        }


        [HttpPost]
        public IActionResult CadastrarProduto(ProdutoViewModel model, int Id)
        {
            if (Id > 0)
            {
                produtoRepository.EditarProduto(model, Id);
            }
            else
            {
                produtoRepository.SalvarProduto(model);
            }
            return RedirectToAction(nameof(ProdutosCadastrados));
        }


        public IActionResult ProdutosCadastrados()
        {
            var IdUsuario = HttpContext.Session.GetInt32("IdUsuario");

            if (IdUsuario != null)
            {
                return View(produtoRepository.GetProdutoList());
            }
            return RedirectToAction("Login", "Usuario");

        }


        public IActionResult EditarProduto(int Id)
        {
            var produto = new ProdutoViewModel()
            {
                GetProduto = produtoRepository.GetProdutoById(Id),
                GetFornecedores = fornecedorRepository.GetFornecedorList()
            };
            return View(nameof(CadProduto), produto);
        }

        public IActionResult ExcluirProduto(int Id)
        {
            produtoRepository.DeleteProduto(Id);
            return RedirectToAction(nameof(ProdutosCadastrados));
        }

        public IActionResult DetalhesDoProduto(int Id)
        {
            return View(produtoRepository.GetProdutoById(Id));
        }

        /*Fim Produto ↑ */

        public IActionResult CadCliente()
        {
            var IdUsuario = HttpContext.Session.GetInt32("IdUsuario");

            if (IdUsuario != null)
            {
                return View();
            }
            return RedirectToAction("Login", "Usuario");
        }

        [HttpPost]
        public IActionResult CadastrarCliente(Cliente cliente, int Id)
        {
            if (ModelState.IsValid && Id > 0)
            {
                clienteRepository.EditarCliente(cliente, Id);
            }
            else
            {
                clienteRepository.SalvarCliente(cliente);
            }
            return RedirectToAction(nameof(ClientesCadastrados));
        }


        public IActionResult ExcluirCliente(int Id)
        {
            clienteRepository.ExcluirCliente(Id);
            return RedirectToAction(nameof(ClientesCadastrados));
        }

        public IActionResult EditarCliente(int Id)
        {
            return View(nameof(CadCliente), clienteRepository.GetClienteById(Id));
        }



        public IActionResult ClientesCadastrados()
        {
            var IdUsuario = HttpContext.Session.GetInt32("IdUsuario");

            if (IdUsuario != null)
            {
                return View(clienteRepository.GetClienteList());
            }
            return RedirectToAction("Login", "Usuario");
        }


        public IActionResult DetalhesDoCliente(int Id)
        {
            return View(clienteRepository.GetClienteById(Id));
        }
        /*Fim Cliente ↑ */

        public IActionResult CadFuncionario()
        {
            var IdUsuario = HttpContext.Session.GetInt32("IdUsuario");

            if (IdUsuario != null)
            {
                return View();
            }
            return RedirectToAction("Login", "Usuario");
        }

        [HttpPost]
        public IActionResult CadastrarFuncionario(Funcionario funcionario, int Id)
        {
            if (Id > 0)
            {
                funcionarioRepository.EditarFuncionario(funcionario, Id);
            }
            else
            {
                funcionarioRepository.SalvarFuncionario(funcionario);
            }
            return RedirectToAction(nameof(FuncionariosCadastrados));
        }


        public IActionResult FuncionariosCadastrados()
        {
            var IdUsuario = HttpContext.Session.GetInt32("IdUsuario");

            if (IdUsuario != null)
            {
                return View(funcionarioRepository.GetFuncionarioList());
            }
            return RedirectToAction("Login", "Usuario");
        }

        public IActionResult EditarFuncionario(int Id)
        {
            return View(nameof(CadFuncionario), funcionarioRepository.GetFuncionarioById(Id));
        }

        public IActionResult DetalhesDoFuncionario(int Id)
        {
            return View(funcionarioRepository.GetFuncionarioById(Id));
        }

        public IActionResult ExcluirFuncionario(int Id)
        {
            funcionarioRepository.ExcluirFuncionario(Id);

            return RedirectToAction(nameof(FuncionariosCadastrados));
        }
        /*Fim Funcionário ↑ */
        public IActionResult SimularPreco()
        {
            var IdUsuario = HttpContext.Session.GetInt32("IdUsuario");

            if (IdUsuario != null)
            {
                return View();
            }
            return RedirectToAction("Login", "Usuario");
        }
        [HttpPost]
        public IActionResult SimularPreco(SimularPreco simularPreco)
        {
            var precoV = simularPreco.PrecoCompra + ((simularPreco.PrecoCompra * simularPreco.MargeLucro) / 100);

            var simular = new SimularPreco()
            {
                PrecoCompra = simularPreco.PrecoCompra,
                MargeLucro = simularPreco.MargeLucro,
                PrecoVenda = precoV,
                Lucro = ((simularPreco.PrecoCompra * simularPreco.MargeLucro) / 100),
                MargemBruta = ((simularPreco.MargeLucro / precoV) * 100)
            };
            return View(nameof(ResultadoDaSimulacao), simular);
        }

        public IActionResult ResultadoDaSimulacao()
        {
            var IdUsuario = HttpContext.Session.GetInt32("IdUsuario");

            if (IdUsuario != null)
            {
                return View();
            }
            return RedirectToAction("Login", "Usuario");
        }
        /*Fim Simulação de Preço ↑ */


        public IActionResult CadVenda()
        {
            var IdUsuario = HttpContext.Session.GetInt32("IdUsuario");

StockControl/StockControl/StockControl/Views/Cadastros/CadCliente.cshtml
@model Cliente

@{
    ViewData["Title"] = "CadCliente";
    <!--Autor:Novadson Thelus-->
}

@using (Html.BeginForm("CadastrarCliente", "Cadastros", FormMethod.Post))
{
    <style>
        .row {
            margin-left: 10px;
            margin-right: 10px;
        }
    </style>

    <div class="panel panel-default  pull-right col-lg-8  col-md-7 col-sm-7 col-xl panelWidth">
        <div class="panel-heading">Cadastro de Cliente</div>

        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Nome" class="control-label">Nome Completo:</label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="CpfCnpj" class="control-label">Cpf/Cnpj:</label>
                    <input asp-for="CpfCnpj" class="form-control cpfCnpj" />
                    <span asp-validation-for="CpfCnpj" class="text-danger"></span>
                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Rg" class="control-label">Rg:</label>
                    <input asp-for="Rg" data-mask="99.999.999-9" class="form-control" />
                    <span asp-validation-for="Rg" class="text-danger"></span>
                </div>
            </div>

            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Cep" class="control-label">Cep:</label>
                    <input asp-for="Cep" name="CEP" data-mask="99.999.999" class="form-control" />
                    <span asp-validation-for="Cep" class="text-danger"></span>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Pais" class="control-label">País:</label>
                    <input asp-for="Pais" id="pais" class="form-control" />
                    <span asp-validation-for="Pais" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Uf" class="control-label">UF:</label>
                    <input asp-for="Uf" id="uf" class="form-control" />
                    <span asp-validation-for="Uf" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Cidade" class="control-label">Cidade:</label>
                    <input asp-for="Cidade" id="cidade" class="form-control" />
                    <span asp-validation-for="Cidade" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Bairro" class="control-label">Bairro</label>
                    <input asp-for="Bairro" id="bairro" class="form-control" />
                    <span asp-validation-for="Bairro" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Rua" class="control-label"></label>
                    <input asp-for="Rua" id="rua" class="form-control" />
                    <span asp-validation-for="Rua" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Numero" class="control-label">Número:</label>
                    <input asp-for="Numero" class="form-control" />
                    <span asp-validation-for="Numero" class="text-danger"></span>
                </div>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Email" class="control-label">Email:</label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>

            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Celular" class="control-label">Contato:</label>
                    <input asp-for="Celular" class="form-control tel" />
                    <span asp-validation-for="Celular" class="text-danger"></span>
                </div>
            </div>

        </div>

        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="form-group ">
                    <button id="btnSalvar" onclick="Confirm()" type="Submit" class="btn btn-success"><i class="glyphicon glyphicon-saved"></i>Salvar</button>
                    <a asp-action="ClientesCadastrados" class="btn btn-info"><i class="glyphicon glyphicon-backward"></i>Voltar</a>
                </div>
            </div>

            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label class="col-lg-4 col-md-2 control-label" id="labelTOP">Ativar</label>
                    <input name="Status" value="true" type="checkbox" class="option-input checkbox col-lg-2" checked />
                </div>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
        </div>
    </div>

    @if (Model != null)
    {
        <input type="number" class="none" name="Id" value="@Model.Id" />
    }
}

@section Scripts{
    <script src="~/js/site.js"></script>
    <script>
        $('input[name="CEP"]').blur(function () {
            var cep = $(this).val().replace(/\D/g, '');
            if (cep != "") {
                var validacep = /^[0-9]{8}$/;
                if (validacep.test(cep)) {
                    $("#pais").val("...");
                    $("#rua").val("...");
                    $("#bairro").val("...");
                    $("#cidade").val("...");
                    $("#uf").val("...");
                    $("#ibge").val("...");
                    $.getJSON("https://viacep.com.br/ws/" + cep + "/json/?callback=?", function (dados) {
                        if (!("erro" in dados)) {
                            $('#pais').val("Brasil")
                            $('#pais').attr('readonly', true);
                            $("#rua").val(dados.logradouro);
                            $("#rua").attr('readonly', true);
                            $("#bairro").val(dados.bairro);
                            $('#bairro').attr('readonly', true);
                            $("#cidade").val(dados.localidade);
                            $("#cidade").attr('readonly', true);
                            $("#uf").val(dados.uf);
                            $("#uf").attr('readonly', true);
                            $("#numero").focus();
                        } else {
                            limpa_formulário_cep();
                            alert("CEP não encontrado.");
                        };
                    });
                } else {
                    limpa_formulário_cep();
                    alert("Formato de CEP inválido.");
                };
            } else {
                limpa_formulário_cep();
            }
        });



    </script>
}

StockControl/StockControl/StockControl/Views/Cadastros/CadFornecedor.cshtml
@{
    ViewData["Title"] = "CadFornecedor";
    <!--Autor:Novadson Thelus-->
}
@model Fornecedor;

@using (Html.BeginForm("CadastrarFornecedor", "Cadastros", FormMethod.Post))
{
    <style>
        .row {
            margin-left: 10px;
            margin-right: 10px;
        }
    </style>
    <div class="panel panel-default  pull-right col-lg-8  col-md-7 col-sm-7 col-xl panelWidth">
        <div class="panel-heading">Cadastro de Fornecedor</div>

        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Nome" class="control-label">Nome:</label>
                    <input asp-for="Nome" class="form-control" placeholder="Digite o nome do Fornecedor" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
            </div>

            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Cnpj" class="control-label">Cnpj:</label>
                    <input asp-for="Cnpj" class="form-control" data-mask="99.999.999/9999-99" placeholder="99.999.999/9999-99" />
                    <span asp-validation-for="Cnpj" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="TipoEstabelecimento" class="control-label">Tipo de Estabelecimento:</label>
                    <select asp-for="TipoEstabelecimento" class="form-control" required="required">
                        <option selected disabled="disabled">--Selecione o tipo--</option>
                        <option value="Matriz">Matriz</option>
                        <option value="Filial">Filial</option>
                    </select>
                </div>
            </div>

            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Contato" class="control-label">Contato:</label>
                    <input asp-for="Contato" class="form-control" data-mask="(99)9999.9999" placeholder="(99)9999.9999" />
                    <span asp-validation-for="Contato" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" placeholder="nome@gmail.com" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Cep" class="control-label"></label>
                    <input asp-for="Cep" name="CEP" class="form-control" data-mask="99.999-999" placeholder="99.999-999" />
                    <span asp-validation-for="Cep" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Pais" class="control-label">País:</label>
                    <input asp-for="Pais" id="pais" class="form-control" />
                    <span asp-validation-for="Pais" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Uf" class="control-label">UF:</label>
                    <input asp-for="Uf" id="uf" class="form-control" />
                    <span asp-validation-for="Uf" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Cidade" class="control-label">Cidade:</label>
                    <input asp-for="Cidade" id="cidade" class="form-control" />
                    <span asp-validation-for="Cidade" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Bairro" class="control-label">Bairro</label>
                    <input asp-for="Bairro" id="bairro" class="form-control" />
                    <span asp-validation-for="Bairro" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Rua" class="control-label"></label>
                    <input asp-for="Rua" id="rua" class="form-control" />
                    <span asp-validation-for="Rua" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="Numero" class="control-label">Número:</label>
                    <input asp-for="Numero" class="form-control" />
                    <span asp-validation-for="Numero" class="text-danger"></span>
                </div>
            </div>
        </div>
  
        <div class="row">
            <div class="col-md-6 col-xs-6">
                <div class="form-group ">
                    <button id="btnSalvar" onclick="Confirm()" type="Submit" class="btn btn-success"><i class="glyphicon glyphicon-saved"></i>Salvar</button>
                    <a asp-action="FornecedoresCadastrados" class="btn btn-info"><i class="glyphicon glyphicon-backward"></i>Voltar</a>
                </div>
            </div>

            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label class="col-lg-4 col-md-2 control-label" id="labelTOP">Ativar</label>
                    <input name="Status" value="true" type="checkbox" class="option-input checkbox col-lg-2" checked />
                </div>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
        </div>
    </div>

        <!--Condição para edição-->
        if (Model != null)
        {
        <input type="number" name="Id" class="none" value="@(Model.Id)" />
        }
        }
        <div id="myModal" class="modal-dialog modal-confirm modal fade">
            <div class="modal-content">
                <div class="modal-header">
                    <div class="icon-box">
                        <i class="material-icons">
                            done
                        </i>
                    </div>
                    <h4 class="modal-title">Sucesso!</h4>
                </div>
                <div class="modal-body">
                    <p class="text-center"> Registro Salvo Com Sucesso!</p>
                </div>
                <div class="modal-footer">

                    <a asp-action="FornecedoresCadastrados" class="btn btn-success btn-block">
                        <p class="centromodal">Ok</p>
                    </a>
                </div>
            </div>
        </div>



        @section Scripts{
            <script>


                $('.sucess').on('click', function () {
                    $.dialog({
                        title: 'Text content!',
                        content: 'Simple modal!',
                        buttons: {
                            aRandomButton: function () {
                                // this will be removed.
                            }
                        }
                    });
                });

                $('input[name="CEP"]').blur(function () {
                    var cep = $(this).val().replace(/\D/g, '');
                    if (cep != "") {
                        var validacep = /^[0-9]{8}$/;
                        if (validacep.test(cep)) {
                            $("#pais").val("...");
                            $("#rua").val("...");
                            $("#bairro").val("...");
                            $("#cidade").val("...");
                            $("#uf").val("...");
                            $("#ibge").val("...");
                            $.getJSON("https://viacep.com.br/ws/" + cep + "/json/?callback=?", function (dados) {
                                if (!("erro" in dados)) {
                                    $('#pais').val("Brasil")
                                    $('#pais').attr('readonly', true);
                                    $("#rua").val(dados.logradouro);
                                    $("#rua").attr('readonly', true);
                                    $("#bairro").val(dados.bairro);
                                    $('#bairro').attr('readonly', true);
                                    $("#cidade").val(dados.localidade);
                                    $("#cidade").attr('readonly', true);
                                    $("#uf").val(dados.uf);
                                    $("#uf").attr('readonly', true);
                                    $("#numero").focus();
                                } else {
                                    limpa_formulário_cep();
                                    alert("CEP não encontrado.");
                                };
                            });
                        } else {
                            limpa_formulário_cep();
                            alert("Formato de CEP inválido.");
                        };
                    } else {
                        limpa_formulário_cep();
                    }
                });


            </script>
        }

StockControl/StockControl/StockControl/Views/Cadastros/CadVenda.cshtml
@model VendaViewModel;

@{
    ViewData["Title"] = "CadVenda";
    <!--Autor:Novadson Thelus-->
}

}
@using (Html.BeginForm("CadastrarVenda", "Cadastros", FormMethod.Post))
{
    <style>
        .row {
            margin-left: 10px;
            margin-right: 10px;
        }
    </style>

    <div class="panel panel-default  pull-right col-lg-8  col-md-7 col-sm-7 col-xl panelWidth">
        <div class="panel-heading">Cadastro de Vendas</div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label">Vendedor:</label>
                    <select name="SelectedFuncionario" asp-for="GetVenda.Funcionario.Id"
                            asp-items="@( new SelectList(Model.GetFuncionarios, "Id", "Nome"))" required class="form-control"></select>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label">Produto:</label>
                    <select name="SelectedProduto" asp-for="GetVenda.Produto.Id"
                            asp-items="@( new SelectList(Model.GetProdutos, "Id", "Descricao"))" required class="form-control"></select>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="control-label">Cliente:</label>
                    <select name="SelectedCliente" asp-for="GetVenda.Cliente.Id"
                            asp-items="@( new SelectList(Model.GetClientes, "Id", "Nome"))" required class="form-control"></select>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="GetVenda.Quantidade" class="control-label">Quantidade de Item:</label>
                    <input asp-for="GetVenda.Quantidade" class="form-control" placeholder="Digita a quantidade de item" />
                    <span asp-validation-for="GetVenda.Quantidade" class="text-danger"></span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="GetVenda.Comissao" class="control-label">Comissão de Vendedor:</label>
                    <input asp-for="GetVenda.Comissao" class="form-control" placeholder="Digite o valor da comissão" />
                    <span asp-validation-for="GetVenda.Comissao" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6 col-xs-6">
                <div class="form-group">
                    <label asp-for="GetVenda.Tipo" class="control-label">Tipo:</label>
                    <select asp-for="GetVenda.Tipo" class="form-control" required="required">
                        <option selected disabled="disabled">--Selecione o tipo--</option>
                        <option value="Venda">Venda</option>
                        <option value="Orçamento">Orçamento</option>
                    </select>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group ">
                    <button id="btnSalvar" onclick="Confirm()" type="Submit" class="btn btn-success"><i class="glyphicon glyphicon-saved"></i>Salvar</button>
                    <a asp-action="VendasCadastradas" class="btn btn-info"><i class="glyphicon glyphicon-backward"></i>Voltar</a>
                </div>
            </div>

        </div>
    </div>

    @if (Model.GetVenda != null)
    {
        <input type="number" class="none" name="Id" value="@Model.GetVenda.Id" />
    }
}